### ISSUE TITLE
marker_assisted

### ISSUE THREAD

**Issue by zhoudreames** [arangrhie/T2T-Polish#1]
I got errors when I run the marker_assisted code：

the code is 
java -cp  marker_assisted/src/SubFile chr1.filteredList chr1.tmp2.sam >>chr1.tmp.sam
the errors is 
Error: Could not find or load main class Mochr1_MotherHap.filteredList
when i see the src dictory code,there isn't SubFile files,instead of have SubFile.java 、SubFile.class and SubFile$Pair.class codes.
that's why? thank ~

**Comment by skoren** [comment]
Your java usage is wrong, -cp is a class path to a directory to search, it shouldn't include SubFile. Your command should be:
```
java -cp marker_assisted/src/ SubFile chr1.filteredList chr1.tmp2.sam >>chr1.tmp.sam
```
You can see this is how it is run in the shell scripts in this repo, e.g.: https://github.com/arangrhie/T2T-Polish/blob/a91aef9e8266c93ec803802dffc738720c91503e/marker_assisted/merge.sh. You should try basic troubleshooting of your command yourself before posting issues.

**Comment by zhoudreames** [comment]
thanks~
