### ISSUE TITLE
racon: invalid option -- 'L'

### ISSUE THREAD

**Issue by YilinZhang449** [arangrhie/T2T-Polish#4]
Hello,
I am getting following error message:
racon: invalid option -- 'L'

I run Racon -h and find that there are no -L and -S parameters which used in the Automated Polishing pipeline. How can I solve this problem?
Thank you !

**Comment by arangrhie** [comment]
Hello, the `-L` and `-S` options are only available in the liftover branch: https://github.com/isovic/racon/tree/liftover
Please check out this branch version and try again.

Thanks!

**Comment by tinyfallen** [comment]
> Hello, the `-L` and `-S` options are only available in the liftover branch: https://github.com/isovic/racon/tree/liftover Please check out this branch version and try again.
> 
> Thanks!

Hi dear developer,

I downloaded the release file at https://github.com/isovic/racon/releases/download/1.4.3/racon-v1.4.3.tar.gz or followed the installation description to git clone --recursive the branch and make some effort to compile racon which both ran smoothly, however it still have no -L and -S options available. Could you please give me some suggestions?

Thanks!

**Comment by tinyfallen** [comment]
Hi @arangrhie ,

Sorry to bother, I have noticed what went wrong because I was not familiar with git branch. I added -b liftover option to git clone so that it's OK.

Best~

tiny

**Comment by Hanjiangna** [comment]
hello
my code :git clone -b liftover  https://github.com/isovic/racon/tree/liftover
erro as follows
Cloning into 'liftover'...
fatal: repository 'https://github.com/isovic/racon/tree/liftover/' not found

**Comment by tinyfallen** [comment]
已收到您发送的邮件！
