### ISSUE TITLE
racon: invalid option -- 'L'

### ISSUE THREAD

**Issue by btrainee** [arangrhie/T2T-Polish#7]
Dear : 

I encountered the same situation，Could you tell me how to solve it ?
![image](https://github.com/arangrhie/T2T-Polish/assets/40187286/3873c23d-5d4c-4c6e-ae3d-2fdaeadd7403)

Best Wishes!

**Comment by arangrhie** [comment]
Hello, please see the conversation in https://github.com/arangrhie/T2T-Polish/issues/4. Let me know if you still have the same issue after switching the branch.

Arang

**Comment by btrainee** [comment]
> Hello, please see the conversation in #4. Let me know if you still have the same issue after switching the branch.
> 
> Arang
Sorry, I made the same mistake. Now that it's ok ! Thank you~
