### ISSUE TITLE
a binary executable for racon liftover branch?

### ISSUE THREAD

**Issue by STF003** [arangrhie/T2T-Polish#8]
Hi arangrhie,

I'm not familiar with the git branch. I installed the racon liftover branch with the following command. However, I made some errors.

Could you provide a binary executable for the racon liftover branch or the racon liftover branch installer package, or give me some suggestions?

Thanks!

``` 
git clone -b liftover https://github.com/lbcb-sci/racon.git racon

Cloning into 'racon'...
fatal: Remote branch liftover not found in upstream origin

**Comment by adriludwig** [comment]
Hi [aijigekoukou-shen](https://github.com/aijigekoukou-shen),
Just in case... this was my solution:
git clone https://github.com/isovic/racon.git
cd racon
git checkout liftover
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make

**Comment by arangrhie** [comment]
Thanks @adriludwig !
