### ISSUE TITLE
racon git branch error

### ISSUE THREAD

**Issue by Hanjiangna** [arangrhie/T2T-Polish#9]
hello
my code :
git clone -b liftover  https://github.com/isovic/racon/tree/liftover
erro :
atal: repository 'https://github.com/isovic/racon/tree/liftover/' not found

**Comment by arangrhie** [comment]
See #8 .
```
git clone https://github.com/isovic/racon.git
cd racon
git checkout liftover
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```

**Comment by Hanjiangna** [comment]
Thanks for your reply very much
